#!/bin/bash
# shellcheck disable=SC1091
# shellcheck disable=SC2086
# shellcheck disable=SC2034
# shellcheck disable=SC2155

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/.config/omzsh"
ZSH_THEME="bira"

HIST_STAMPS="mm.dd.yyyy"

# Plugins
plugins=(
    bin
    cake
    composer
    dnf
    eza
    fzf
    git
    hellwal
    httpie
    laravel
    node
    npm
    nvim
    ssh
    ssh-agent
    tmux
    vscode
    wp-cli
    terminal
    zoxide
)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export ARCHFLAGS="-arch $(uname -m)"
